export const customTitles: { [key: string]: string } = {
  '/info': 'Info',
  '/domains': 'Domains',
  '/backup': 'Backup',
  '/tools': 'Tools',
  '/redirects': 'Redirects',
  '/themesandplugins': 'Themes and plugins',
  '/addons': 'Add-ons',
  '/ipdeny': 'IP Deny',
  '/analytics': 'Analytics',
  '/caching': 'Caching',
  '/users': 'Users management',
  '/logs': 'Logs',
  '/wpsites': 'WordPress sites',
  '/plans': 'My Plan',
  '/invoices': 'Invoices',
  '/paymentmethods': 'Payment methods',
  '/billing': 'Billing details',
  '/refferals': 'Refferals',
  '/apikeys': 'API keys',
  '/registry': 'Registry credentials',
  '/userssettings': 'Users',
  '/sitelabels': 'Site labels',
  '/useractivity': 'User activity',
  '/personalInfo': 'Personal info',
  '/access': 'Access',
  '/notifications': 'Notifications',
};
