export const dummyClone = [
  { value: 'us-central', label: 'Iowa (US Central)' },
  { value: 'us-east', label: 'South Carolina (US East)' },
  { value: 'us-west', label: 'Oregon (US West)' },
  { value: 'asia-east', label: 'Taiwan (Asia East)' },
  { value: 'asia-northeast', label: 'Tokyo (Asia Northeast)' },
  { value: 'asia-southeast', label: 'Singapore (Asia Southeast)' },
  { value: 'australia-southeast', label: 'Sydney (Australia Southeast)' },
  { value: 'europe-north', label: 'Finland (Europe North)' },
  { value: 'europe-west', label: 'Belgium (Europe West)' },
  { value: 'southamerica-east', label: 'São Paulo (South America East)' },
  { value: 'asia-south', label: 'Mumbai (Asia South)' },
  { value: 'canada-central', label: 'Montreal (Canada Central)' },
  { value: 'europe-west2', label: 'London (Europe West 2)' },
  { value: 'europe-west3', label: 'Frankfurt (Europe West 3)' },
  { value: 'europe-west4', label: 'Netherlands (Europe West 4)' },
];
